"""create users table

Revision ID: 8dad372a1f24
Revises:
Create Date: 2026-04-24 12:44:37.964808

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8dad372a1f24"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "user_id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
            comment="회원 내부 PK",
        ),
        sa.Column(
            "email", sa.String(length=100), nullable=False, comment="로그인 ID (이메일)"
        ),
        sa.Column(
            "password",
            sa.String(length=255),
            nullable=False,
            comment="비밀번호 해시 (bcrypt)",
        ),
        sa.Column("name", sa.String(length=50), nullable=True, comment="이름"),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="계정 상태: ACTIVE / LOCKED / DORMANT",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="생성 시각",
        ),
        sa.Column(
            "created_by",
            sa.BigInteger(),
            nullable=True,
            comment="생성자 user_id (회원가입 시에는 null)",
        ),
        sa.Column(
            "created_ip", sa.String(length=45), nullable=True, comment="생성 요청 IP"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="최종 수정 시각",
        ),
        sa.Column(
            "updated_by", sa.BigInteger(), nullable=True, comment="최종 수정자 user_id"
        ),
        sa.Column(
            "updated_ip",
            sa.String(length=45),
            nullable=True,
            comment="최종 수정 요청 IP",
        ),
        # sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='삭제 여부 (소프트 삭제)'),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
            comment="삭제 여부 (소프트 삭제)",
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
