"""add data_source column to job_postings

Revision ID: b8050fd5e470
Revises: d2e3f4a5b6c7
Create Date: 2026-04-30 17:07:51.368236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8050fd5e470'
down_revision: Union[str, Sequence[str], None] = 'd2e3f4a5b6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batch_job_runs', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment='배치 대상 출처 (ALIO/WORK24 등)',
               existing_nullable=True)
    op.alter_column('common_code_groups', 'group_id',
               existing_type=sa.BIGINT(),
               comment='공통코드 그룹 PK',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('common_code_groups', 'category_code',
               existing_type=sa.VARCHAR(length=30),
               comment='대분류 코드 (REC/INST 등)',
               existing_nullable=False)
    op.alter_column('common_code_groups', 'code_group',
               existing_type=sa.VARCHAR(length=30),
               comment='코드 그룹 (R1000/A2000 등)',
               existing_nullable=False)
    op.alter_column('common_code_groups', 'code_group_name',
               existing_type=sa.VARCHAR(length=100),
               comment='코드 그룹명',
               existing_nullable=False)
    op.alter_column('common_code_groups', 'description',
               existing_type=sa.TEXT(),
               comment='설명',
               existing_nullable=True)
    op.alter_column('common_code_groups', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='활성 여부',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('common_code_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시각',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('common_code_groups', 'created_by',
               existing_type=sa.BIGINT(),
               comment='생성자 user_id (회원가입 시에는 null)',
               existing_nullable=True)
    op.alter_column('common_code_groups', 'created_ip',
               existing_type=sa.VARCHAR(length=45),
               comment='생성 요청 IP',
               existing_nullable=True)
    op.alter_column('common_code_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='최종 수정 시각',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('common_code_groups', 'updated_by',
               existing_type=sa.BIGINT(),
               comment='최종 수정자 user_id',
               existing_nullable=True)
    op.alter_column('common_code_groups', 'updated_ip',
               existing_type=sa.VARCHAR(length=45),
               comment='최종 수정 요청 IP',
               existing_nullable=True)
    op.alter_column('common_code_groups', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='삭제 여부 (소프트 삭제)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('common_codes', 'code_id',
               existing_type=sa.BIGINT(),
               comment='공통상세코드 PK',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('common_codes', 'code_group',
               existing_type=sa.VARCHAR(length=30),
               comment='코드 그룹',
               existing_nullable=False)
    op.alter_column('common_codes', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='상세 코드',
               existing_nullable=False)
    op.alter_column('common_codes', 'code_name',
               existing_type=sa.VARCHAR(length=200),
               comment='코드명',
               existing_nullable=False)
    op.alter_column('common_codes', 'code_description',
               existing_type=sa.TEXT(),
               comment='코드 설명',
               existing_nullable=True)
    op.alter_column('common_codes', 'parent_code',
               existing_type=sa.VARCHAR(length=50),
               comment='상위 코드',
               existing_nullable=True)
    op.alter_column('common_codes', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='정렬 순서',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('common_codes', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='활성 여부',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('common_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시각',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('common_codes', 'created_by',
               existing_type=sa.BIGINT(),
               comment='생성자 user_id (회원가입 시에는 null)',
               existing_nullable=True)
    op.alter_column('common_codes', 'created_ip',
               existing_type=sa.VARCHAR(length=45),
               comment='생성 요청 IP',
               existing_nullable=True)
    op.alter_column('common_codes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='최종 수정 시각',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('common_codes', 'updated_by',
               existing_type=sa.BIGINT(),
               comment='최종 수정자 user_id',
               existing_nullable=True)
    op.alter_column('common_codes', 'updated_ip',
               existing_type=sa.VARCHAR(length=45),
               comment='최종 수정 요청 IP',
               existing_nullable=True)
    op.alter_column('common_codes', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='삭제 여부 (소프트 삭제)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('job_postings', sa.Column('data_source', sa.String(length=20), server_default='PRODUCTION', nullable=False, comment='데이터 출처 (PRODUCTION/MOCK/MANUAL)'))
    op.alter_column('job_postings', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment='공고 출처 (ALIO/WORK24/SARAMIN/MANUAL)',
               existing_comment='공고 출처 (WORK24/SARAMIN/MANUAL)',
               existing_nullable=False)
    op.alter_column('job_postings', 'source_job_id',
               existing_type=sa.VARCHAR(length=100),
               comment='외부 공고 ID',
               existing_comment='외부 공고 ID (Work24의 wantedAuthNo)',
               existing_nullable=True)
    op.alter_column('job_postings', 'location_code',
               existing_type=sa.VARCHAR(length=20),
               comment='근무지 코드 (ALIO R3000)',
               existing_nullable=True)
    op.alter_column('job_postings', 'career_level_code',
               existing_type=sa.VARCHAR(length=20),
               comment='채용구분 코드 (ALIO R2000)',
               existing_nullable=True)
    op.alter_column('job_postings', 'education_code',
               existing_type=sa.VARCHAR(length=20),
               comment='학력정보 코드 (ALIO R7000)',
               existing_nullable=True)
    op.alter_column('job_postings', 'ncs_category',
               existing_type=sa.VARCHAR(length=200),
               comment='NCS 분류명',
               existing_nullable=True)
    op.alter_column('job_postings', 'ncs_category_code',
               existing_type=sa.VARCHAR(length=20),
               comment='NCS 분류 코드 (ALIO R6000)',
               existing_nullable=True)
    op.alter_column('job_postings', 'organization_type',
               existing_type=sa.VARCHAR(length=100),
               comment='기관유형',
               existing_nullable=True)
    op.alter_column('job_postings', 'organization_type_code',
               existing_type=sa.VARCHAR(length=20),
               comment='기관유형 코드 (ALIO A2000)',
               existing_nullable=True)
    op.alter_column('job_postings', 'organization_category',
               existing_type=sa.VARCHAR(length=100),
               comment='기관분류',
               existing_nullable=True)
    op.alter_column('job_postings', 'organization_category_code',
               existing_type=sa.VARCHAR(length=30),
               comment='기관분류 코드 (ALIO INST_CLSF)',
               existing_nullable=True)
    op.alter_column('job_postings', 'ministry',
               existing_type=sa.VARCHAR(length=100),
               comment='주무부처',
               existing_nullable=True)
    op.alter_column('job_postings', 'ministry_code',
               existing_type=sa.VARCHAR(length=20),
               comment='주무부처 코드 (ALIO A1000)',
               existing_nullable=True)
    op.alter_column('job_postings', 'updated_from_source_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='외부 출처 기준 최종수정일',
               existing_nullable=True)
    op.create_index(op.f('ix_job_postings_data_source'), 'job_postings', ['data_source'], unique=False)
    # job_sources 컬럼 comment 변경 및 기존 unique constraint 유지
    op.alter_column('job_sources', 'source_id',
               existing_type=sa.BIGINT(),
               comment='채용공고 수집원 PK',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('job_sources', 'source_code',
               existing_type=sa.VARCHAR(length=20),
               comment='수집원 코드 (ALIO/WORK24/SARAMIN/MANUAL)',
               existing_nullable=False)
    op.alter_column('job_sources', 'source_name',
               existing_type=sa.VARCHAR(length=100),
               comment='수집원 이름',
               existing_nullable=False)
    op.alter_column('job_sources', 'status',
               existing_type=sa.VARCHAR(length=30),
               comment='ACTIVE/DISABLED/PENDING_APPROVAL/DEPRECATED',
               existing_nullable=False)
    op.alter_column('job_sources', 'disabled_reason',
               existing_type=sa.TEXT(),
               comment='비활성/보류 사유',
               existing_nullable=True)
    op.alter_column('job_sources', 'base_url',
               existing_type=sa.VARCHAR(length=500),
               comment='수집원 기본 URL',
               existing_nullable=True)
    op.alter_column('job_sources', 'last_checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='마지막 상태 확인 시각',
               existing_nullable=True)
    op.alter_column('job_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시각',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_sources', 'created_by',
               existing_type=sa.BIGINT(),
               comment='생성자 user_id (회원가입 시에는 null)',
               existing_nullable=True)
    op.alter_column('job_sources', 'created_ip',
               existing_type=sa.VARCHAR(length=45),
               comment='생성 요청 IP',
               existing_nullable=True)
    op.alter_column('job_sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='최종 수정 시각',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_sources', 'updated_by',
               existing_type=sa.BIGINT(),
               comment='최종 수정자 user_id',
               existing_nullable=True)
    op.alter_column('job_sources', 'updated_ip',
               existing_type=sa.VARCHAR(length=45),
               comment='최종 수정 요청 IP',
               existing_nullable=True)
    op.alter_column('job_sources', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='삭제 여부 (소프트 삭제)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # job_sources_source_code_key unique constraint는 모델에 unique=True가 유지되므로 제거하지 않음
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_sources', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='삭제 여부 (소프트 삭제)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('job_sources', 'updated_ip',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='최종 수정 요청 IP',
               existing_nullable=True)
    op.alter_column('job_sources', 'updated_by',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='최종 수정자 user_id',
               existing_nullable=True)
    op.alter_column('job_sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='최종 수정 시각',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_sources', 'created_ip',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='생성 요청 IP',
               existing_nullable=True)
    op.alter_column('job_sources', 'created_by',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='생성자 user_id (회원가입 시에는 null)',
               existing_nullable=True)
    op.alter_column('job_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성 시각',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_sources', 'last_checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='마지막 상태 확인 시각',
               existing_nullable=True)
    op.alter_column('job_sources', 'base_url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='수집원 기본 URL',
               existing_nullable=True)
    op.alter_column('job_sources', 'disabled_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='비활성/보류 사유',
               existing_nullable=True)
    op.alter_column('job_sources', 'status',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='ACTIVE/DISABLED/PENDING_APPROVAL/DEPRECATED',
               existing_nullable=False)
    op.alter_column('job_sources', 'source_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='수집원 이름',
               existing_nullable=False)
    op.alter_column('job_sources', 'source_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='수집원 코드 (ALIO/WORK24/SARAMIN/MANUAL)',
               existing_nullable=False)
    op.alter_column('job_sources', 'source_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='채용공고 수집원 PK',
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_job_postings_data_source'), table_name='job_postings')
    op.alter_column('job_postings', 'updated_from_source_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='외부 출처 기준 최종수정일',
               existing_nullable=True)
    op.alter_column('job_postings', 'ministry_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='주무부처 코드 (ALIO A1000)',
               existing_nullable=True)
    op.alter_column('job_postings', 'ministry',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='주무부처',
               existing_nullable=True)
    op.alter_column('job_postings', 'organization_category_code',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='기관분류 코드 (ALIO INST_CLSF)',
               existing_nullable=True)
    op.alter_column('job_postings', 'organization_category',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='기관분류',
               existing_nullable=True)
    op.alter_column('job_postings', 'organization_type_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='기관유형 코드 (ALIO A2000)',
               existing_nullable=True)
    op.alter_column('job_postings', 'organization_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='기관유형',
               existing_nullable=True)
    op.alter_column('job_postings', 'ncs_category_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='NCS 분류 코드 (ALIO R6000)',
               existing_nullable=True)
    op.alter_column('job_postings', 'ncs_category',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='NCS 분류명',
               existing_nullable=True)
    op.alter_column('job_postings', 'education_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='학력정보 코드 (ALIO R7000)',
               existing_nullable=True)
    op.alter_column('job_postings', 'career_level_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='채용구분 코드 (ALIO R2000)',
               existing_nullable=True)
    op.alter_column('job_postings', 'location_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='근무지 코드 (ALIO R3000)',
               existing_nullable=True)
    op.alter_column('job_postings', 'source_job_id',
               existing_type=sa.VARCHAR(length=100),
               comment='외부 공고 ID (Work24의 wantedAuthNo)',
               existing_comment='외부 공고 ID',
               existing_nullable=True)
    op.alter_column('job_postings', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment='공고 출처 (WORK24/SARAMIN/MANUAL)',
               existing_comment='공고 출처 (ALIO/WORK24/SARAMIN/MANUAL)',
               existing_nullable=False)
    op.drop_column('job_postings', 'data_source')
    op.alter_column('common_codes', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='삭제 여부 (소프트 삭제)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('common_codes', 'updated_ip',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='최종 수정 요청 IP',
               existing_nullable=True)
    op.alter_column('common_codes', 'updated_by',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='최종 수정자 user_id',
               existing_nullable=True)
    op.alter_column('common_codes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='최종 수정 시각',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('common_codes', 'created_ip',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='생성 요청 IP',
               existing_nullable=True)
    op.alter_column('common_codes', 'created_by',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='생성자 user_id (회원가입 시에는 null)',
               existing_nullable=True)
    op.alter_column('common_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성 시각',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('common_codes', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='활성 여부',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('common_codes', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='정렬 순서',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('common_codes', 'parent_code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='상위 코드',
               existing_nullable=True)
    op.alter_column('common_codes', 'code_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='코드 설명',
               existing_nullable=True)
    op.alter_column('common_codes', 'code_name',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='코드명',
               existing_nullable=False)
    op.alter_column('common_codes', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='상세 코드',
               existing_nullable=False)
    op.alter_column('common_codes', 'code_group',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='코드 그룹',
               existing_nullable=False)
    op.alter_column('common_codes', 'code_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='공통상세코드 PK',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('common_code_groups', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='삭제 여부 (소프트 삭제)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('common_code_groups', 'updated_ip',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='최종 수정 요청 IP',
               existing_nullable=True)
    op.alter_column('common_code_groups', 'updated_by',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='최종 수정자 user_id',
               existing_nullable=True)
    op.alter_column('common_code_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='최종 수정 시각',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('common_code_groups', 'created_ip',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='생성 요청 IP',
               existing_nullable=True)
    op.alter_column('common_code_groups', 'created_by',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='생성자 user_id (회원가입 시에는 null)',
               existing_nullable=True)
    op.alter_column('common_code_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성 시각',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('common_code_groups', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='활성 여부',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('common_code_groups', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='설명',
               existing_nullable=True)
    op.alter_column('common_code_groups', 'code_group_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='코드 그룹명',
               existing_nullable=False)
    op.alter_column('common_code_groups', 'code_group',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='코드 그룹 (R1000/A2000 등)',
               existing_nullable=False)
    op.alter_column('common_code_groups', 'category_code',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='대분류 코드 (REC/INST 등)',
               existing_nullable=False)
    op.alter_column('common_code_groups', 'group_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='공통코드 그룹 PK',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('batch_job_runs', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='배치 대상 출처 (ALIO/WORK24 등)',
               existing_nullable=True)
    # ### end Alembic commands ###
