"""add job_postings and batch_job_runs tables

Revision ID: b9a9c0967b9a
Revises: 4f6a7b8c9d10
Create Date: 2026-04-30 11:06:56.924728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9a9c0967b9a'
down_revision: Union[str, Sequence[str], None] = '4f6a7b8c9d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_job_runs',
    sa.Column('run_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='배치 실행 PK'),
    sa.Column('job_code', sa.String(length=50), nullable=False, comment='배치 코드 (WORK24_COLLECT/JOB_CLOSE_SYNC/JOB_EMBEDDING 등)'),
    sa.Column('job_name', sa.String(length=200), nullable=False, comment='배치 이름'),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True, comment='중복 실행 방지용 키'),
    sa.Column('status', sa.String(length=20), server_default='READY', nullable=False, comment='READY/RUNNING/SUCCESS/FAILED/PARTIAL_SUCCESS/SKIPPED/RATE_LIMITED'),
    sa.Column('trigger_type', sa.String(length=20), nullable=False, comment='MANUAL/SCHEDULED/RETRY'),
    sa.Column('triggered_by', sa.String(length=50), nullable=True, comment='관리자 user_id 또는 SYSTEM'),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='실행 시 keyword, startPage, display, region, occupation 등'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('collected_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('inserted_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_code', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='생성자 user_id (회원가입 시에는 null)'),
    sa.Column('created_ip', sa.String(length=45), nullable=True, comment='생성 요청 IP'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='최종 수정 시각'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='최종 수정자 user_id'),
    sa.Column('updated_ip', sa.String(length=45), nullable=True, comment='최종 수정 요청 IP'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='삭제 여부 (소프트 삭제)'),
    sa.PrimaryKeyConstraint('run_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_batch_job_runs_job_code'), 'batch_job_runs', ['job_code'], unique=False)
    op.create_index(op.f('ix_batch_job_runs_status'), 'batch_job_runs', ['status'], unique=False)
    op.create_table('job_postings',
    sa.Column('job_id', sa.BigInteger(), autoincrement=True, nullable=False, comment='채용공고 PK'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='공고 출처 (WORK24/SARAMIN/MANUAL)'),
    sa.Column('source_job_id', sa.String(length=100), nullable=True, comment='외부 공고 ID (Work24의 wantedAuthNo)'),
    sa.Column('source_url', sa.String(length=500), nullable=True, comment='원문 URL (wantedInfoUrl)'),
    sa.Column('mobile_url', sa.String(length=500), nullable=True, comment='모바일 URL (wantedMobileInfoUrl)'),
    sa.Column('company_name', sa.String(length=200), nullable=True, comment='회사명'),
    sa.Column('business_number', sa.String(length=20), nullable=True, comment='사업자등록번호'),
    sa.Column('industry', sa.String(length=200), nullable=True, comment='업종'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='채용제목'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='근무지역 텍스트'),
    sa.Column('location_address', sa.String(length=500), nullable=True, comment='근무지 전체주소'),
    sa.Column('career_level', sa.String(length=50), nullable=True, comment='경력조건 텍스트'),
    sa.Column('min_career_years', sa.Integer(), nullable=True),
    sa.Column('max_career_years', sa.Integer(), nullable=True),
    sa.Column('education', sa.String(length=50), nullable=True, comment='학력조건'),
    sa.Column('employment_type', sa.String(length=50), nullable=True, comment='고용형태'),
    sa.Column('employment_type_code', sa.String(length=20), nullable=True),
    sa.Column('work_schedule', sa.String(length=200), nullable=True, comment='근무시간/형태'),
    sa.Column('salary_type', sa.String(length=20), nullable=True, comment='임금형태 (D/H/M/Y)'),
    sa.Column('salary_text', sa.String(length=500), nullable=True, comment='급여 원문'),
    sa.Column('min_salary', sa.Integer(), nullable=True),
    sa.Column('max_salary', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True, comment='등록일자'),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True, comment='마감일/접수마감일'),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True, comment='외부 API 최종수정일 (smodifyDtm)'),
    sa.Column('raw_content', sa.Text(), nullable=True, comment='직무내용 + 기타 안내 텍스트 통합본'),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='외부 API 원본 응답 (XML->dict 변환)'),
    sa.Column('parsed_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='추출된 스킬/키워드 리스트'),
    sa.Column('hash_signature', sa.String(length=64), nullable=True, comment='변경 감지용 SHA256'),
    sa.Column('status', sa.String(length=20), server_default='OPEN', nullable=False, comment='공고 상태 (OPEN/CLOSED/EXPIRED/HIDDEN)'),
    sa.Column('collection_status', sa.String(length=20), server_default='COLLECTED', nullable=False, comment='수집/후처리 상태 (COLLECTED/PARSED/EMBEDDED/FAILED)'),
    sa.Column('embedding_status', sa.String(length=20), server_default='PENDING', nullable=False, comment='임베딩 처리 상태 (PENDING/COMPLETED/FAILED)'),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수집 시각'),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collect_run_id', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='생성자 user_id (회원가입 시에는 null)'),
    sa.Column('created_ip', sa.String(length=45), nullable=True, comment='생성 요청 IP'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='최종 수정 시각'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='최종 수정자 user_id'),
    sa.Column('updated_ip', sa.String(length=45), nullable=True, comment='최종 수정 요청 IP'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='삭제 여부 (소프트 삭제)'),
    sa.ForeignKeyConstraint(['collect_run_id'], ['batch_job_runs.run_id'], ),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('source', 'source_job_id', name='uq_job_postings_source')
    )
    op.create_index(op.f('ix_job_postings_collected_at'), 'job_postings', ['collected_at'], unique=False)
    op.create_index(op.f('ix_job_postings_company_name'), 'job_postings', ['company_name'], unique=False)
    op.create_index(op.f('ix_job_postings_deadline'), 'job_postings', ['deadline'], unique=False)
    op.create_index(op.f('ix_job_postings_hash_signature'), 'job_postings', ['hash_signature'], unique=False)
    op.create_index(op.f('ix_job_postings_location'), 'job_postings', ['location'], unique=False)
    op.create_index(op.f('ix_job_postings_posted_at'), 'job_postings', ['posted_at'], unique=False)
    op.create_index(op.f('ix_job_postings_source'), 'job_postings', ['source'], unique=False)
    op.create_index(op.f('ix_job_postings_source_job_id'), 'job_postings', ['source_job_id'], unique=False)
    op.create_index(op.f('ix_job_postings_status'), 'job_postings', ['status'], unique=False)
    op.create_index(op.f('ix_job_postings_title'), 'job_postings', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_postings_title'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_status'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_source_job_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_source'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_posted_at'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_location'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_hash_signature'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_deadline'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_company_name'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_collected_at'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_batch_job_runs_status'), table_name='batch_job_runs')
    op.drop_index(op.f('ix_batch_job_runs_job_code'), table_name='batch_job_runs')
    op.drop_table('batch_job_runs')
    # ### end Alembic commands ###
