"""
Application-wide error codes.
"""

from enum import StrEnum


class ErrorCode(StrEnum):
    """Stable error codes used by the backend and frontend."""

    VALIDATION_ERROR = "COMMON_001"
    NOT_FOUND = "COMMON_404"
    METHOD_NOT_ALLOWED = "COMMON_405"
    INTERNAL_SERVER_ERROR = "COMMON_500"

    UNAUTHORIZED = "AUTH_001"
    FORBIDDEN = "AUTH_002"
    DUPLICATE_EMAIL = "AUTH_003"
    INVALID_CREDENTIALS = "AUTH_004"
    INACTIVE_USER = "AUTH_005"
    REFRESH_TOKEN_MISSING = "AUTH_006"
    INVALID_REFRESH_TOKEN = "AUTH_007"

    CATEGORY_NOT_FOUND = "CATEGORY_001"
    DUPLICATE_CATEGORY_SLUG = "CATEGORY_002"

    POST_NOT_FOUND = "POST_001"
    POST_CATEGORY_NOT_FOUND = "POST_002"

    RESUME_NOT_FOUND = "RESUME_001"
    RESUME_FILE_TOO_LARGE = "RESUME_002"
    RESUME_UNSUPPORTED_FILE_TYPE = "RESUME_003"
    RESUME_NOT_PARSED = "RESUME_006"

    # 이력서 면접 연습 (OpenAI)
    OPENAI_API_KEY_MISSING = "OPENAI_API_KEY_MISSING"
    INTERVIEW_SESSION_NOT_FOUND = "INTERVIEW_SESSION_NOT_FOUND"
    INTERVIEW_QUESTION_NOT_FOUND = "INTERVIEW_QUESTION_NOT_FOUND"
    INTERVIEW_QUESTION_GENERATION_FAILED = "INTERVIEW_QUESTION_GENERATION_FAILED"
    INTERVIEW_ANSWER_EVALUATION_FAILED = "INTERVIEW_ANSWER_EVALUATION_FAILED"

    APPLICATION_ALREADY_EXISTS = "APPLICATION_001"

    COMPANY_NOT_FOUND = "COMPANY_001"

    JOB_NOT_FOUND = "JOB_001"
    JOB_COLLECTION_FAILED = "JOB_002"
    EXTERNAL_JOB_API_FAILED = "JOB_003"
    JOB_API_PARSE_FAILED = "JOB_004"
    JOB_API_KEY_MISSING = "JOB_005"
    JOB_SOURCE_UNAVAILABLE = "JOB_SOURCE_001"

    BATCH_JOB_FAILED = "BATCH_001"
    BATCH_JOB_RUN_NOT_FOUND = "BATCH_002"

    CODE_NOT_FOUND = "CODE_001"
