"""
Application-wide error codes.
"""

from enum import StrEnum


class ErrorCode(StrEnum):
    """Stable error codes used by the backend and frontend."""

    VALIDATION_ERROR = "COMMON_001"
    NOT_FOUND = "COMMON_404"
    METHOD_NOT_ALLOWED = "COMMON_405"
    INTERNAL_SERVER_ERROR = "COMMON_500"

    UNAUTHORIZED = "AUTH_001"
    FORBIDDEN = "AUTH_002"
    DUPLICATE_EMAIL = "AUTH_003"
    INVALID_CREDENTIALS = "AUTH_004"
    INACTIVE_USER = "AUTH_005"
    REFRESH_TOKEN_MISSING = "AUTH_006"
    INVALID_REFRESH_TOKEN = "AUTH_007"

    CATEGORY_NOT_FOUND = "CATEGORY_001"
    DUPLICATE_CATEGORY_SLUG = "CATEGORY_002"

    POST_NOT_FOUND = "POST_001"
    POST_CATEGORY_NOT_FOUND = "POST_002"

    RESUME_NOT_FOUND = "RESUME_001"
    RESUME_FILE_TOO_LARGE = "RESUME_002"
    RESUME_UNSUPPORTED_FILE_TYPE = "RESUME_003"
    RESUME_NOT_PARSED = "RESUME_006"

    # 이력서 면접 연습 (OpenAI)
    OPENAI_API_KEY_MISSING = "OPENAI_API_KEY_MISSING"
    INTERVIEW_SESSION_NOT_FOUND = "INTERVIEW_SESSION_NOT_FOUND"
    INTERVIEW_QUESTION_NOT_FOUND = "INTERVIEW_QUESTION_NOT_FOUND"
    INTERVIEW_QUESTION_GENERATION_FAILED = "INTERVIEW_QUESTION_GENERATION_FAILED"
    INTERVIEW_ANSWER_EVALUATION_FAILED = "INTERVIEW_ANSWER_EVALUATION_FAILED"

    APPLICATION_ALREADY_EXISTS = "APPLICATION_001"
    APPLICATION_NOT_FOUND = "APPLICATION_002"
    APPLICATION_INVALID_STATUS = "APPLICATION_003"

    COMPANY_NOT_FOUND = "COMPANY_001"
    INTERVIEW_EMAIL_FAILED = "COMPANY_002"

    LEAVE_REQUEST_NOT_FOUND = "LEAVE_001"
    LEAVE_INVALID_STATUS = "LEAVE_002"
    LEAVE_INSUFFICIENT_BALANCE = "LEAVE_003"
    LEAVE_APPROVER_NOT_FOUND = "LEAVE_004"
    LEAVE_INVALID_REQUEST = "LEAVE_005"

    # 이메일/계정 찾기/비밀번호 재설정
    EMAIL_SEND_FAILED = "EMAIL_001"
    EMAIL_NOT_CONFIGURED = "EMAIL_002"
    PASSWORD_RESET_INVALID_CODE = "EMAIL_003"
    EMAIL_RATE_LIMITED = "EMAIL_004"

    JOB_NOT_FOUND = "JOB_001"
    JOB_COLLECTION_FAILED = "JOB_002"
    EXTERNAL_JOB_API_FAILED = "JOB_003"
    JOB_API_PARSE_FAILED = "JOB_004"
    JOB_API_KEY_MISSING = "JOB_005"
    JOB_NOT_EDITABLE = "JOB_006"
    JOB_SOURCE_UNAVAILABLE = "JOB_SOURCE_001"

    BATCH_JOB_FAILED = "BATCH_001"
    BATCH_JOB_RUN_NOT_FOUND = "BATCH_002"

    CODE_NOT_FOUND = "CODE_001"

    USER_NOT_FOUND = "USER_001"

    # RBAC 역할 부여/회수
    ROLE_NOT_FOUND = "ROLE_001"
    ROLE_ALREADY_ASSIGNED = "ROLE_002"
    ROLE_NOT_ASSIGNED = "ROLE_003"
    ROLE_SELF_SUPER_ADMIN_REVOKE = "ROLE_004"
    ROLE_LAST_SUPER_ADMIN = "ROLE_005"
